name: Run tests on a schedule

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v2
      - name: use playwright to test
        env:
          NODE_OPTIONS: "--max-old-space-size=6144"
        run: |
          yarn --version
          npm --version
          node --version
          ls -a
          yarn
          npx playwright install
          sudo npx playwright install-deps 
          yarn run playwright test --update-snapshots
          yarn run playwright test --browser=all
      - run: git config user.name "Kushal";
        if: always()
      - run: git config user.email "kushal@gmx.com";
        if: always()
      - run: git add .;
        if: always()
      - run: git commit -m "run playwright tests" -m "on the cloud";
        if: always()
      - run: git pull --rebase --strategy-option=theirs;
        if: always()
      - run: git push origin master;
        if: always()
