name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v2
      - name: use playwright to test
        env:
          NODE_OPTIONS: "--max-old-space-size=6144"
        run: |
          yarn --version
          npm --version
          node --version
          ls -a
          yarn
          npx playwright install
          sudo npx playwright install-deps
          yarn run playwright test --browser=all --config=tests/config.ts
          yarn run playwright test --config=tests/mobile.ts
