name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: use playwright to test
        uses: actions/checkout@v2
        env:
          NODE_OPTIONS: "--max-old-space-size=6144"
        run: |
          yarn --version
          npm --version
          node --version
          ls -a
          yarn
          yarn run playwright test --update-snapshots
          yarn run playwright test --browser=all
