name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
        export NODE_OPTIONS="--max-old-space-size=6144" && yarn && yarn run build
        npx playwright install
        yarn
        npx playwright test --update-snapshots
        npx playwright test --browser=all
