name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: use playwright to test
        run: |
          export NODE_OPTIONS="--max-old-space-size=6144"
          yarn --version
          npm --version
          node --version
          ls -a
          npx playwright install
          yarn
          npx playwright test --update-snapshots
          npx playwright test --browser=all
